### ISSUE TITLE
Your discord link is not working!

### ISSUE THREAD

**Issue by detherminal** [Kotlin-Discord/meta#2]
All you have to do is just managing a discord server but you dont even have a discord link to join your server @gdude2002 @Scotsguy @Akarys42

**Comment by pluiedev** [comment]
I believe it was removed for a while due to spambot raids. Should be okay to add it back now.

Also, chillax.

**Comment by detherminal** [comment]
@leocth but how can normal people join. Can you send me a temporary link for discord?

**Comment by gdude2002** [comment]
Duplicate of site#14 -  see [this comment](https://github.com/Kotlin-Discord/site/issues/14#issuecomment-972771632) specifically.

I don't appreciate your tone, so you can find the invite on your own. If you do manage to find it and join, I hope you're less combative - you won't last long with this attitude.
